apiVersion: apps/v1
kind: Deployment
metadata:
  name: card-deployment
  labels:
    app: card
spec:
  replicas: 1
  selector:
    matchLabels:
      app: card
  template:
    metadata:
      labels:
        app: card
    spec:
      containers:
      - name: card
        image: rosered/twelve-factor-card:amd64
        ports:
        - containerPort: 8088
        # livenessProbe:
        #   failureThreshold: 3
        #   exec:
        #     command:
        #     - /bin/sh
        #     - -c
        #     - 'curl -s https://my-config-server.herokuapp.com/card/prod | grep -c "env"'
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
          # successThreshold: 1
          # timeoutSeconds: 1
        # readinessProbe:
        #   failureThreshold: 3
        #   exec:
        #     command:
        #     - /bin/sh
        #     - -c
        #     - 'curl -s https://my-config-server.herokuapp.com/card/prod | grep -c "env"'
        #   periodSeconds: 10
          # successThreshold: 1
          # timeoutSeconds: 1
        env:
        - name: Eureka__Client__ServiceUrl
          value: "http://eurekaserver-service:8761/eureka/"
        - name: Eureka__Client__ValidateCertificates
          value: "false"
        - name: Eureka__Instance__HostName
          value: "card-service"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: Logging__LogLevel__Default
          value: "Debug"
        - name: Logging__LogLevel__Steeltoe
          value: "Debug"
        - name: Urls
          value: "http://*:8088"

---
apiVersion: v1
kind: Service
metadata:
  name: card-service
spec:
  selector:
    app: card
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088