apiVersion: apps/v1
kind: Deployment
metadata:
  name: card-deployment
  labels:
    app: card
spec:
  replicas: 1
  selector:
    matchLabels:
      app: card
  template:
    metadata:
      labels:
        app: card
    spec:
      containers:
      - name: card
        image: rosered/twelve-factor-card:arm64
        lifecycle:
          postStart:
            exec:
              command: 
              - /bin/sh
              - -c
              - 'apt update & apt install curl -y'
        ports:
        - containerPort: 8090
        # livenessProbe:
        #   failureThreshold: 3
        #   exec:
        #     command:
        #     - /bin/sh
        #     - -c
        #     - 'curl -s http://configserver-service:8888/card/prod | grep -c "env"'
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        #   successThreshold: 1
        #   timeoutSeconds: 1
        # readinessProbe:
        #   failureThreshold: 3
        #   exec:
        #     command:
        #     - /bin/sh
        #     - -c
        #     - 'curl -s http://configserver-service:8888/card/prod | grep -c "env"'
        #   periodSeconds: 10
        #   successThreshold: 1
        #   timeoutSeconds: 1
        env:
        - name: Eureka__Client__ServiceUrl
          value: "http://eurekaserver-service:8761/eureka/"
        - name: Eureka__Client__ValidateCertificates
          value: "false"
        - name: Eureka__Instance__HostName
          value: "card-service"
        - name: Urls
          value: "http://*:8090"
        - name: Spring__Cloud__Config__Uri
          value: http://configserver-service:8888

---
apiVersion: v1
kind: Service
metadata:
  name: card-service
spec:
  selector:
    app: card
  type: NodePort
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
      nodePort: 30202