apiVersion: apps/v1
kind: Deployment
metadata:
  name: card-deployment
  labels:
    app: card
spec:
  replicas: 1
  selector:
    matchLabels:
      app: card
  template:
    metadata:
      labels:
        app: card
    spec:
      containers:
      - name: card
        image: rosered/twelve-factor-card:amd64
        #image: rosered/myapp
        ports:
        - containerPort: 5080
        env:
        - name: Eureka__Client__ServiceUrl
          value: "http://eurekaserver-service:8761/eureka/"
        - name: Eureka__Client__ValidateCertificates
          value: "false"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: Logging__LogLevel__Default
          value: "Debug"
        - name: Logging__LogLevel__Steeltoe
          value: "Debug"
        - name: Urls
          value: "http://*:5080"

---
apiVersion: v1
kind: Service
metadata:
  name: card-service
spec:
  selector:
    app: card
  #type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 5080