global:
  scrape_interval:  5s # Set the scrape interval to every 5 seconds.
  evaluation_interval:  5s # Evaluate rules every 5 seconds.
scrape_configs:
  - job_name: 'cards'
    metrics_path: '/metrics'
    static_configs:
    - targets: ['cards:8090']
  - job_name: 'accounts'
    metrics_path: '/metrics'
    static_configs:
    - targets: ['accounts:8091']