version: "3.8"

services:
  eurekaserver:
    image: rosered/eureka
    mem_limit: 700m
    ports:
      - "8761:8761"
    # networks:
    #   - rosered
    # environment:
    #   Eureka__Client__ServiceUrl: http://localhost:8761/eureka
    #   Eureka__Client__ShouldFetchRegistry: false
    #   Eureka__Client__ValidateCertificates: false
  card:
    image: rosered/twelve-factor-card:latest
    mem_limit: 700m
    ports:
      - "80:80"
    # networks:
    #   - rosered
    depends_on:
      - eurekaserver
    environment:
      Eureka__Client__ServiceUrl: http://eurekaserver:8761/eureka
      Eureka__Client__ShouldFetchRegistry: false
    #  Eureka__Client__ValidateCertificates: false
      Eureka__Instance__LeaseRenewalIntervalInSeconds: 15
      Eureka__Instance__Hostname: localhost
      Eureka__Instance__Port: 80
  account:
    image: rosered/twelve-factor-account:latest
    mem_limit: 700m
    ports:
      - "81:81"
    # networks:
    #   - rosered
    depends_on:
      - eurekaserver
    environment:
      Eureka__Client__ServiceUrl: http://eurekaserver:8761/eureka
      Eureka__Client__ShouldFetchRegistry: false
    #  Eureka__Client__ValidateCertificates: false
      Eureka__Instance__LeaseRenewalIntervalInSeconds: 15
      Eureka__Instance__Hostname: localhost
      Eureka__Instance__Port: 81
# networks:
#   rosered: