apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-control-plane
  labels:
    app: kong-control-plane
spec:
  selector:
    matchLabels:
      app: kong-control-plane
  template:
    metadata:
      labels:
        app: kong-control-plane
    spec:
      containers:
      - name: kong-control-plane
        image: kong
        imagePullPolicy: IfNotPresent
        env:
          - name: KONG_DATABASE
            value: postgres
          - name: KONG_PG_PASSWORD
            value: kong
          - name: KONG_PG_HOST
            value: postgres-service
          - name: KONG_LOG_LEVEL
            value: notice
          - name: KONG_ADMIN_ACCESS_LOG
            value: /dev/stdout
          - name: KONG_PROXY_ERROR_LOG
            value: /dev/stderr
          - name: KONG_ADMIN_ERROR_LOG
            value: /dev/stderr
          - name: KONG_ADMIN_LISTEN
            value: 0.0.0.0:8001,0.0.0.0:8444 ssl
          
          # - name: KONG_PROXY_LISTEN
          #   value: 'off'
          # - name: KONG_ADMIN_SSL_CERT
          #   value: /api-server-cert/tls.crt
          # - name: KONG_ADMIN_SSL_CERT_KEY
          #   value: /api-server-cert/tls.key
          # - name: KONG_NGINX_WORKER_PROCESSES
          #   value: "1"
        # volumeMounts:
        #   - name: api-server-cert
        #     mountPath: /api-server-cert
        ports:
        - name: admin-http
          containerPort: 8001
        - name: admin-https
          containerPort: 8444
        # livenessProbe:
        #   failureThreshold: 3
        #   httpGet:
        #     path: /status
        #     port: 8001
        #     scheme: HTTP
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        #   successThreshold: 1
        #   timeoutSeconds: 1
        # readinessProbe:
        #   failureThreshold: 3
        #   httpGet:
        #     path: /status
        #     port: 8001
        #     scheme: HTTP
        #   periodSeconds: 10
        #   successThreshold: 1
        #   timeoutSeconds: 1
      # volumes:
      # - name: api-server-cert
      #   secret:
      #     secretName: kong-control-plane.kong.svc
---
apiVersion: v1
kind: Service
metadata:
  name: kong-control-plane
spec:
  type: NodePort
  ports:
    - name: admin-http
      port: 8001
      targetPort: 8001
      nodePort: 30002
  selector:
    app: kong-control-plane