apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-deployment
  labels:
    app: account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
      - name: account
        image: rosered/twelve-factor-account:arm64
        ports:
        - containerPort: 8091
          # livenessProbe:
          #   failureThreshold: 3
          #   exec:
          #     command:
          #     - /bin/sh
          #     - -c
          #     - 'curl -s https://my-config-server.herokuapp.com/account/prod | grep -c "accounts.msg"'
          # initialDelaySeconds: 30
          # periodSeconds: 10
          # successThreshold: 1
          # timeoutSeconds: 1
        env:
        - name: Eureka__Client__ServiceUrl
          value: "http://eurekaserver-service:8761/eureka/"
        - name: Eureka__Client__ValidateCertificates
          value: "false"
        - name: Eureka__Instance__HostName
          value: "account-service"
        - name: Urls
          value: "http://*:8091"
        - name: Spring__Cloud__Config__Uri
          value: http://configserver-service:8888

---
apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  selector:
    app: account
  type: NodePort
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
      nodePort: 30201